<div class="HomeMain">

    <header>
        <h1 style="color:#333; font-size: 3em; text-align: center;">
            Lorem Ipsum Cars ti da il Benvenuto!
        </h1>  
        <br>
        <img style="width: 1100px;" src="<?= $this->baseUrl('css/media/immagineHome.png') ?>">
        <br>
    </header>

    <hr>

    <section class="sectionHome">

        <section class="sectionHomeElem1">

            <h3 style="color:#333">
                La Nostra Missione
            </h3> 

            Noleggiare un'auto non è mai stato così semplice! <br>
            Il nostro obbiettivo è trovare l'auto giusta per voi al miglior prezzo; 
            il nostro team altamente qualificato è pronto ad aiutarvi in ogni momento
            per ogni vostra esigenza. <br>

            <b>Voi pensate a guidare, noi pensiamo a tutto il resto!</b>
        </section>         

        <section class="sectionHomeElem2">

            <h3 style="color:#333">
                Dove Trovarci
            </h3>

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26761.863849633028!2d13.49054296134715!3d43.588800864390265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x161719e4f3f5daaf!2sUniversit%C3%A0+Politecnica+delle+Marche+-+Facolt%C3%A0+di+Ingegneria!5e0!3m2!1sit!2sit!4v1555174690253!5m2!1sit!2sit" id='Mappa' ></iframe> 

        </section> 

    </section>
</div>

