<h3>
    Benvenuto nella tua area riservata
</h3>

<nav>
    <a href="<?= $this->url(array(
                    'controller' => 'staff',
                    'action'     => 'staffarea',
                    'operazione'       => 'inserisci',
                ), 
                    'default',true
                ); 
             ?>" title="Inserisci">     
    Inserisci una nuova auto
    </a>
    
    <br>
    
    <a href="<?= $this->url(array(
                    'controller' => 'staff',
                    'action'     => 'staffarea',
                    'operazione'       => 'elimina',
                ), 
                    'default',true
                ); 
             ?>" title="Elimina">     
    Elimina un'auto
    </a>
    
    <br>
    
    <a href="<?= $this->url(array(
                    'controller' => 'staff',
                    'action'     => 'staffarea',
                    'operazione'       => 'modifica',
                ), 
                    'default',true
                ); 
             ?>" title="Modifica">     
    Modifica i dati di un'auto
    </a>
    
    <br>
    
    <a href="<?= $this->url(array(
                    'controller' => 'staff',
                    'action'     => 'staffarea',
                    'operazione' => 'statistiche',
                ), 
                    'default',true
                ); 
             ?>" title="Statistiche">     
    Statistiche delle prenotazioni
    </a>
    
</nav>

<div>
    
    <?php if($this->operazione === "inserisci"): ?>
    <h4>Inserisci la nuova Auto</h4>
        <?php echo $this->inserisciForm; ?>
    <?php endif; ?>
    
    <?php if ($this->operazione === "elimina"): ?>
    <h4>Inserisci la targa dell'auto che vuoi eliminare</h4>
        <?php echo $this->eliminaForm;?>
    <?php endif; ?>
    
    <?php if($this->operazione === "modifica"): ?>
        
    <?php endif; ?>
    
    <?php if($this->operazione === "statistiche"): ?>
        
    <?php endif; ?>
    
    
</div>

