<?php if ($this->authInfo('role') === "admin"): ?>
    <h2 class="headerAdmin">
        Area Riservata Amministratore
    </h2>
<?php else: ?>
    <h2 class="headerAdmin">
        Area Riservata Staff
    </h2>
<?php endif; ?>


<nav class="barraNavigazioneStaff">

    <?php if ($this->authInfo('role') === "admin"): ?>
        <a href="<?=
        $this->url(array(
            'controller' => 'admin',
            'action' => 'adminarea',
                ), 'default', true
        );
        ?>" title="Area Riservata Admin">
            Funzionalità dell'Admin
        </a>

    <?php endif; ?>

    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
        'operazione' => 'inserisci',
            ), 'default', true
    );
    ?>" title="Inserisci">     
        Inserisci una nuova auto
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
        'operazione' => 'elimina',
            ), 'default', true
    );
    ?>" title="Elimina">     
        Elimina un'auto
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
        'operazione' => 'seleziona',
            ), 'default', true
    );
    ?>" title="Modifica">     
        Modifica i dati di un'auto
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
        'operazione' => 'statistiche',
            ), 'default', true
    );
    ?>" title="Statistiche" style="border-right: 2px solid #333">     
        Statistiche per Mese
    </a>

</nav>


<?php if ($this->operazione === "inserisci"): ?>
    <h3 class="headerAdmin">
        Inserimento di una nuova auto
    </h3>
    <fieldset class="styleformstaff" >
        <?php echo $this->inserisciForm; ?>
    </fieldset>
<?php endif; ?>

<?php if ($this->operazione === "elimina"): ?>
    <h3 class="headerAdmin">
        Eliminazione di un'auto esistente
    </h3>

    <fieldset style="float: left; width: 300px; clear:both;">
        <legend> <h3 class="headerAdmin"> Scegli la targa dell'auto da eliminare </h3> </legend>
        <?php echo $this->eliminaForm; ?>
    </fieldset>

    <div style="margin-left: 400px">
        <table class="tableAdmin" style="width: 600px;" border="">
            <tr><th style="width: 400px"> Modello </th> <th style="width: 200px"> Targa </th> </tr>
        </table>
        <?php foreach ($this->auto as $auto) : ?>
            <table class="tableAdmin" style="width: 600px;" border="">
                <tbody>
                    <tr>
                        <td style="width: 400px"><?php echo '' . $auto->marca . " " . $auto->modello . '' ?></td>
                        <td style="width: 200px"><?php echo'' . $auto->targa . '' ?></td>
                    </tr>
                </tbody>
            </table>
        <?php endforeach ?>
    </div>

<?php endif; ?>

<?php if ($this->operazione === "seleziona"): ?>
    <h3 class="headerAdmin">
        Modifica di un'auto esistente
    </h3>

    <fieldset style="float: left; width: 300px; clear:both;">
        <legend> <h3 class="headerAdmin"> Seleziona la targa dell'auto da modificare </h3> </legend>
        <?php echo $this->selezionaForm; ?>
    </fieldset>

    <div style="margin-left: 400px">
        <table class="tableAdmin" style="width: 600px;" border="">
            <tr><th style="width: 400px"> Modello </th> <th style="width: 200px"> Targa </th> </tr>
        </table>
        <?php foreach ($this->auto as $auto) : ?>
            <table class="tableAdmin" style="width: 600px;" border="">
                <tbody>
                    <tr>
                        <td style="width: 400px"><?php echo '' . $auto->marca . " " . $auto->modello . '' ?></td>
                        <td style="width: 200px"><?php echo'' . $auto->targa . '' ?></td>
                    </tr>
                </tbody>
            </table>
        <?php endforeach ?>
    </div>
<?php endif; ?>

<?php if ($this->operazione === "modifica"): ?>
10:06
<h3 class="headerAdmin">
        Modifica di un'auto esistente
    </h3>
    <fieldset style="width: 400px; margin-left: 350px">
        <legend> <h3 class="headerAdmin"> Inserisci i nuovi dati </h3> </legend>
        <?php echo $this->modificaForm->populate($this->macchina); ?>
    </fieldset>

<?php endif; ?>

<?php if ($this->operazione === "statistiche"): ?>
    <h3 class="headerAdmin">
        Statistiche delle prenotazioni per mese
    </h3>

    <fieldset class="styleformstaff">
        <legend> <h3> Seleziona il mese </h3> </legend>
        <?php echo $this->statisticheForm; ?>
    </fieldset>

    <br>

    <div style=" margin-left: 100px">
        <table class="tableAdmin" style="width: 900px;" border="">
            <tr>
                <th style="width: 225px"> Username </th> 
                <th style="width: 225px"> Targa </th> 
                <th style="width: 225px"> Marca </th> 
                <th style="width: 225px"> Modello </th> 
            </tr>
        </table>

        <?php foreach ($this->prenotazioni as $prenotazione) : ?>
            <table class="tableAdmin" style="width: 900px;" border="">
                <tbody>
                    <tr>
                        <td style="width: 225px"><?php echo '' . $prenotazione->username . '' ?></td>
                        <td style="width: 225px"><?php echo'' . $prenotazione->targa . '' ?></td>
                        <td style="width: 225px"><?php echo'' . $prenotazione->marca . '' ?></td>
                        <td style="width: 225px"><?php echo'' . $prenotazione->modello . '' ?></td>
                    </tr>
                </tbody>
            </table>
        <?php endforeach ?>

    </div>
<?php endif; ?>