<div class="ChisiamoMain">
    <div id="presentazione">
        <h1>Chi siamo?</h1>

        <p>
            <b style="font-size: 19px">Siamo la scelta giusta per te!</b>
            <br>
        </p>
        <p>
            Da più di due mesi gestiamo la nostra azienda come una grande famiglia e garantiamo ai nostri clienti un servizio impeccabile.<br>
            Non lo diciamo noi.<br> Parlano i fatti: il 90% dei nostri clienti ci descrive come la miglior agenzia di noleggio auto del territorio.
        </p>
        <ul id="ChisiamoList">

            <li>Ampia scelta</li>
            <li>Affidabilità</li>
            <li>Convenienza</li>
        </ul>
        <p>
            Queste sono le parole chiave che meglio identificano la <b>Lorem Ipsum Car</b>.
        </p>
        <p>
            Vienici a trovare ad Ancona in <a href="https://www.google.com/maps/place/Universit%C3%A0+Politecnica+delle+Marche+-+Facolt%C3%A0+di+Ingegneria/@43.5867829,13.5144063,17z/data=!3m1!4b1!4m5!3m4!1s0x132d80233dd931ef:0x161719e4f3f5daaf!8m2!3d43.586779!4d13.516595">Via Breccia Bianche 12</a>
            oppure usa i nostri contatti per prendere un appuntamento senza impegno:<br>
            <br>
            Chiamaci allo <a href="callto:071 220 4708">071 220 4708</a>
            <br>
            Scrivi una mail al nostro Ufficio Clienti: <a href="mailto:loremipsumcar@rent.it">loremipsumcar@rent.it</a>
        </p>
    </div>

    <img id=ChisiamoImg1 src="<?= $this->baseUrl('css/media/chisiamoimg.jpg') ?>" >


</div>


