<h1 style="color:#333; font-size: 2em; text-align: center;">
    FAQ
</h1>

<div class="faq">
    <?php foreach ($this->faq as $faq) : ?>
    <hr class="barra" style="clear: both; width:1100px; ">
        <section class="faqElem1">
        <h4 style="color:#333; font-size: 1em;">
            <?php echo $faq->domanda ?>
        </h4>
            <?php echo $faq->risposta ?>
            <br><br>
        </section>
    <?php endforeach ?>
</div>