<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'public', 'action' => 'validatelogin',), 'default'); ?>';
	var formName='<?= $this->loginForm->getName() ?>';
	$(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>

<div class="static" style="text-align: center" >
    <?php if( $this->authInfo('role') === 'unregistered'): ?>
        <h3>LOGIN</h3>
        <p> Inserisci le tue credenziali per poter accedere</p>
        <?= $this->loginForm; ?>
    <?php else: ?>
        <h3>Hai già fatto il login</h3>
    <?php endif;?>
</div>