<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'public', 'action' => 'validatelogin',), 'default'); ?>';
	var formName='<?= $this->loginForm->getName() ?>';
	$(".block input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
        
    });
});

$(function()
{
$('div.campi').hide();
$('div.caption p').on('click', function () {
                    var campo = $(this).closest('div.module2').find('div.campi');
                    if (campo.is(':hidden')) {
                        campo.show();
                    } else {
                        campo.hide('fast');
                    }
                });
});
<?php $this->headScript()->captureEnd() ?>


<div class="static">
    <?php if($this->authInfo('role')==='unregistered'): ?>
    <div class="block">
        <h3> LOGIN </h3>
        <p> Inserisci le tue credenziali per accedere. </p>
        <?= $this->loginForm; ?>
    </div>    
    <div class="module2">
        <p>Se non hai un account</p>
        <div class="caption">
            <p style="color: blue; text-decoration: underline">Registrati</p>
        </div>    
        <div class="campi">
            <p>Utilizza questa form per la registrazione</p>
            <?=$this->registerForm; ?>
        </div>
    </div>
    <?php else: ?>

        <h3>Hai già fatto il login</h3>

    <?php endif; ?>
</div>