<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'public', 'action' => 'validatelogin',), 'default'); ?>';
	var formName='<?= $this->loginForm->getName() ?>';
        var actionUrl='<?= $this->url(array('controller' => 'public', 'action' => 'validateregister',), 'default'); ?>';
	var registerName='<?= $this->registerForm->getName() ?>';
	$(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName, registerName);
    });

});


<?php $this->headScript()->captureEnd() ?>

        
        <script type="text/javascript">
        </script>
        <script type="text/javascript">
            $(function () {
                $('div.logform').on('click', function () {
                    var body = $(this).closest('div.static').find('div.reg');
                    if (body.is(':hidden')) {                       
                    } else {
                        body.hide('slow');
                    }
                });
            });
        </script>
        
        <script type="text/javascript">
            $(function () {
                $('div.regform').on('click', function () {
                    var body = $(this).closest('div.static').find('div.log');
                    if (body.is(':hidden')) {                       
                    } else {
                        body.hide('slow');
                    }
                });
            });
        </script>

<div class="static" style="text-align: center" >
    <?php if($this->authInfo('role')==='unregistered'): ?>
    <div class="log">
        <h3 style="font-style: italic;">Login</h3>
        <p> Inserisci le tue credenziali per poter accedere</p>
        <div class="logform">
        <?= $this->loginForm; ?>
        </div>
    </div> 
    <br>
    <div class="reg">
        <h3 style="font-style:italic;">Registrati</h3>
        <p>Utilizza questa form per la registrazione</p>
        <div class="regform">
        <?=$this->registerForm; ?>
        </div>
    </div>
    <?php else: ?>
        <h3>Hai già fatto il login</h3>
    <?php endif; ?>
</div>