<!DOCTYPE html>
<html>    
    <body>
        <div style="margin-left: 30px" class="ServiziMain">
            <h2> Elenco dei Servizi</h2>
            <nav id="navbarservice">
                <p> 
                    Il nostro obiettivo è di rendere il noleggio auto semplice e comodo, come se stessi guidando la tua auto.                  </p>
                <p>
                    Ci impegniamo quotidianamente per garantire la massima libertà durante la tua vacanza o soggiorno e sfruttare tutti i benefici di avere un'automobile sempre disponibile e pronta a soddisfare le tue esigenze.                </p>
                <p>
                Oltre ad una vasta gamma di tariffe vantaggiose per il tuo noleggio auto, ti offriamo anche dei servizi aggiuntivi per viaggiare senza pensieri.
                Il pcchetto BASIC, già inclus, che prevede la limitazione standard di responsabilità per danni, furto (o tentato furto) e incendio. In caso di danni o furto sarai responsabile fino ad un importo massimo variabile a seconda della vettura selezionata.
                Il pacchetto MEDIUM che invece aggiunge la riduzione della tua responsabilità per danni, furto (o tentato furto) e incendio​ al veicolo​ e l'​assicurazione per infortuni ​al ​conducente e ​a​i passeggeri.
                Oppure quello PREMIUM che prevede l'azzeramento di responsabilità per danni, furto (o tentato furto) e incendio ​al veicolo ​e include l'assicurazione ​infortuni per​ conducente e passeggeri e la ​copertura degli effetti personali.
                </section>
            </nav>
            <img src="<?= $this->baseUrl('css/media/servizi.jpg') ?>" id="immagineservizi" alt="servizi car" />
            <section id="contentservizi">
                <b style="font-size: 18px" >Servizi extra per te!</b>
                <br>
                Oltre ad una vasta gamma di tariffe vantaggiose per il tuo noleggio auto, ti offriamo anche dei servizi aggiuntivi per viaggiare senza pensieri: scegli tra i nostri pacchetti quello che più si adatta alle tue esigenze di viaggio come assicurazioni aggiuntive per il conducente, azzeramento della tua responsabilità per danni, furto o incendio al veicolo.    </section>
        </div>
    </body>
</html>