<ul>
	<a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Catalogo">Le nostre auto</a>
                <a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'who'), 
                        'default',true
                    ); 
                 ?>"
		title="Il nostro profilo azienda">Chi siamo</a>
	<a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'about'), 
                        'default',true
                    ); 
                 ?>"
		title="Cosa offriamo">Servizi</a>
        <a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'about'), 
                        'default',true
                    ); 
                 ?>"
		title="Domande Frequenti">Faq</a>
                
</ul>

