       
    <br>
    
    <a href="" title="Cosa offriamo">
        Servizi
    </a>

    <a href="" title="Catalogo">     
        Le Auto
    </a>

            <a href="<?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'chisiamo'
                        ), 
                        'default',true
                    ); 
                 ?>" title="Il nostro profilo azienda">
                Chi siamo
            </a>
    <a href="" title="Domande Frequenti">
        Faq
    </a>


