<?php echo $this->doctype() ?>
<html>
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headTitle(); ?>
    </head>
<body>
    <nav class="barraNavigazione">
        
            <a href="">
                <div id="Logo" alt="Logo"> 
                </div>
            </a>
            <a href="" id="ancoraLogin">
                <div id="Login" alt="Login">
            </div>
            </a>
        
        <?= $this->render('_topnavmain0.phtml') ?>           
    </nav>
            
        

    <footer class="footer">
        <p style="text-align: center; color: white; font-size: 12px">
                @2020 Lorem Ipsum Car. Tutti i diritti non riservati<br>
        Web site powered by Gruppo 8
        </p>
    </footer>

</body>
</html>
