
<?php echo $this->doctype() ?>
<html>
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headTitle(); ?>
    </head>
    
    <body>
   
        <nav class="barraNavigazione">
            <?= $this->render('_topnavmain1.phtml') ?>           
        </nav>
            
        <div id="page">
  		  	  <?php echo $this->layout()->content; ?>
      	<div style="clear: both;">&nbsp;</div>
	</div>

        <footer class="footer">
            <p style="text-align: center; color: white; font-size: 12px">
                    @2020 Lorem Ipsum Car. Tutti i diritti non riservati<br>
            Web site powered by Gruppo 8
            </p>
        </footer>
            
       
    </body>

</html>
