<div class="mainGestioneUtente">
    <table id="table1" border>
        <caption id="caption1" style="font-size: 18px"> <b>Il tuo profilo</b> </caption>
            <tr>
                <th> Username </th> 
                <th> Nome </th>
                <th> Cognome </th>
                <th> Città </th>
                <th> Data di nascita</th>
                <th> Occupazione</th>
                <th> Password</th>
            </tr>
            <tr>
                <td><?php echo $this->utente->username . ' '?></td>
                <td><?php echo $this->utente->nome . ' '?> </td>
                <td> <?php echo $this->utente->cognome . ' '?> </td>
                <td> <?php echo $this->utente->residenza . ' '?> </td>
                <td><?php echo $this->utente->data_nascita . ' '?></td>
                <td><?php echo $this->utente->occupazione . ' '?></td>
                <td><?php echo $this->utente->password . ' '?></td>
            </tr>                  
    </table>
</div>                
<h3>Modifica Profilo</h3> 

<div>
    <?php echo $this->modificaForm->populate($this->utente->username) ?>
</div>

<div class="mainGestioneUtente">
    <table id="table1" border>
        <caption id="caption1" style="font-size: 18px"> <b>Le tue Prenotazioni</b> </caption>
            <tr>
                <th> Targa </th> 
                <th> Data Inizio </th>
                <th> Data Fine </th>
            </tr>
            <?php foreach ($this->prenotazioni as $prenotazione) : ?>
            <tr>
                <td><?php echo $prenotazione->targa . ' '?></td>
                <td><?php echo $prenotazione->data_inizio . ' '?> </td>
                <td> <?php echo $prenotazione->data_fine . ' '?> </td>
            </tr>        
            <?php endforeach ?>
    </table>
</div>  
