<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>


<?php $this->headScript() -> captureEnd() ?>


<div class="catalog">
    <div class="filters">
        <hr style="width: 1098px; margin-left: -16px; color: white">
        <?php echo $this->filterForm ?>
    </div>   
    <h2 style="text-align:center; color: #333;">
        LA NOSTRA FLOTTA
    </h2>
    <?php if($this->empty == 'yes') :?>
        <?php echo '<p style="font-weight:bolder; text-align:center; color:red; margin-bottom:20px;"> ATTENZIONE: Inserisci un periodo di noleggio per poter prenotare un\''
        . 'auto</p>';
        ?>
    <?php endif; ?>
    <?php foreach ($this->auto as $auto) : ?>
        <div class="prod">
            
            <hr class="barracatalogo">
            <div class="contenitore">
               
        ˙        <div style="width: auto; float: left; margin-right: 10px;">
                    <div style="border: 1px solid black; margin:10px;">
                        <?php echo $this->autoImg($auto->foto, array('class' => 'imagefrm'))?>
                    </div>
                </div>
         <h2 style="margin-left: 15px"> <?php echo '' . $auto->marca . " " . $auto->modello ?> </h2>
                <div style="width: auto;">
                    <div class="testoauto">
                        <ul>
                            <li>  <?php echo'Allestimento: ' . $auto->allestimento  ?> </li>
                            <li>  <?php echo'Numero Posti: ' . $auto->numero_posti  ?> </li>
                            <li>  <?php echo'Targa: ' . $auto->targa . '' ?> </li>                 
                        </ul>
                        
                    </div>
                </div>
         
         <a href="
                <?php if($this->empty != 'yes'): ?>
                      <?=
                      $this->url(array(
                      'controller' => 'user',
                      'action'     => 'addorder',
                      'usr'        =>  $this->authInfo('username'),
                      'inizio'     =>  $this->datainizio,
                      'fine'       =>  $this->datafine,
                      'targa'      =>  $auto->targa,                
                      ), 
                     'default',true);
                      ?>
             <?php endif; ?>
            ">
             <div class="buttonuser">
                 <form id="pricebtn">
                     <input type="button" onclick="<?php if($this->empty != 'yes' ):?>
                                                          <?php echo 'alert(\'Prenotazione Effettuata\')' ?>                                                               
                                                   <?php else :?>
                                                          <?php echo 'alert(\'Inserisci prima una data di inizio e una di fine\')' ?>
                                                   <?php endif; ?>                                
                                                  " 
                            value="Noleggia a soli  <?php echo $auto->prezzo_giornaliero . '€' ?>">
                 </form>
            </div>
         </a>
            </div>
        </div>
    <?php endforeach ?>

    <?php
    if ($this->auto instanceof Zend_Paginator) {
        echo '<div style="margin-top:40px; text-align:center;">'.$this->paginationControl($this->auto, 'Sliding', 'public/_paginator.phtml').'</div>';
    }
    ?>
</div>