<h2>
    Area Riservata Amministratore
</h2>

<h3>
    Gestisci gli Utenti Staff
</h3>

<nav style="width: 500px;float: left; margin-left: 1em">
    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
            ), 'default', true
    );
    ?>" title="Operazioni Staff">     
        Funzionalità dello Staff
    </a>

    <br>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'crudstaff',
            ), 'default', true
    );
    ?>" title="Crud Staff">     
        Gestisci Staff
    </a>

    <br>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'deleteuser',
            ), 'default', true
    );
    ?>" title="Elimina Users">     
        Elimina Utenti
    </a>
    
    <br>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'statistiche',
            ), 'default', true
    );
    ?>" title="Statistiche Annuali">     
        Statistiche Annuali
    </a>
    
    <br> 
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'crudfaq',
            ), 'default', true
    );
    ?>" title="Crud Faq">     
        Gestione FAQ
    </a>

</nav>

<fieldset style="float: left" >
    <legend> <h3> Inserisci un nuovo Utente Staff </h3> </legend>
    <?php echo $this->inserisciForm; ?>
</fieldset>

<fieldset style="float: left" >
    <legend> <h3> Modifica o Elimina un Utente Staff </h3> </legend>
    <?php echo $this->crudForm; ?>
</fieldset>

<?php if ($this->user !== null): ?>

    <fieldset style="width: 300px; clear:both;">
        <legend> <h3> Inserisci i nuovi dati </h3> </legend>
        <?php echo $this->modificaForm->populate($this->user);?>
    </fieldset>

<?php endif; ?>