<h2 class="headerAdmin">
    Area Riservata Amministratore
</h2>

<nav class="barraNavigazioneAdmin">
    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
            ), 'default', true
    );
    ?>" title="Operazioni Staff">     
        Funzionalità dello Staff
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'staff',
            ), 'default', true
    );
    ?>" title="Crud Staff">     
        Gestisci Staff
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'user',
            ), 'default', true
    );
    ?>" title="Elimina Users">     
        Elimina Utenti
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'statistiche',
            ), 'default', true
    );
    ?>" title="Statistiche Annuali">     
        Statistiche Annuali
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'faq',
            ), 'default', true
    );
    ?>" title="Crud Faq">     
        Gestione FAQ
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => '',
        'action' => '',
            ), 'default', true
    );
    ?>" title="chat" style="border-right: 2px solid #333;">     
        Vai alla Chat
    </a>

</nav>

<h3 class="headerAdmin">
    Gestisci le Faq
</h3>

<div style="margin-left: 150px">
    <table class="tableAdmin" style="width: 800px;" border="">
        <tr>
            <th style="width: 400px"> ID </th> 
            <th style="width: 400px"> Domanda </th> 
        </tr>
    </table>

    <?php foreach ($this->domande as $domanda) : ?>
    <table class="tableAdmin" style="width: 800px; " border="">
            <tbody>
                <tr>
                    <td style="width: 400px"><?php echo '' . $domanda->id  . '' ?></td>
                    <td style="width: 400px"><?php echo'' . $domanda->domanda . '' ?></td>
                </tr>
            </tbody>
        </table>
    <?php endforeach ?>

</div>

<fieldset style="width: 510px; float: left;">
    <legend> <h3 class="headerAdmin"> Modifica o Elimina una Faq </h3> </legend>
    <?php echo $this->crudFaqForm; ?>
    
    <?php if ($this->faq !== null): ?>

        <h3 class="headerAdmin"> Inserisci i nuovi dati </h3>
        <?php echo $this->modificaFaqForm->populate($this->faq);?>

    <?php endif; ?>
</fieldset>

<fieldset style="width: 510px; ">
    <legend> <h3 class="headerAdmin"> Inserisci una nuova Faq </h3> </legend>
    <?php echo $this->inserisciFaqForm; ?>
</fieldset>

