<h2>
    Area Riservata Amministratore
</h2>

<nav style="width: 500px;float: left; margin-left: 1em">
    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
            ), 'default', true
    );
    ?>" title="Operazioni Staff">     
        Funzionalità dello Staff
    </a>

    <br>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'staff',
            ), 'default', true
    );
    ?>" title="Crud Staff">     
        Gestisci Staff
    </a>

    <br>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'user',
            ), 'default', true
    );
    ?>" title="Elimina Users">     
        Elimina Utenti
    </a>
    
    <br>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'statistiche',
            ), 'default', true
    );
    ?>" title="Statistiche Annuali">     
        Statistiche Annuali
    </a>
    
    <br> 
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'faq',
            ), 'default', true
    );
    ?>" title="Crud Faq">     
        Gestione FAQ
    </a>

</nav>

<h3>
    Gestisci le Faq
</h3>

<fieldset style="float: left" >
    <legend> <h3> Inserisci una nuova Faq </h3> </legend>
    <?php echo $this->inserisciFaqForm; ?>
</fieldset>

<fieldset style="float: left" >
    <legend> <h3> Modifica o Elimina una Faq </h3> </legend>
    <?php echo $this->crudFaqForm; ?>
</fieldset>

<?php if ($this->faq !== null): ?>

    <fieldset style="width: 300px; clear:both;">
        <legend> <h3> Inserisci i nuovi dati </h3> </legend>
        <?php echo $this->modificaFaqForm->populate($this->faq);?>
    </fieldset>

<?php endif; ?>