<h2 class="headerAdmin">
    Area Riservata Amministratore
</h2>

<nav class="barraNavigazioneAdmin">
    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
            ), 'default', true
    );
    ?>" title="Operazioni Staff">     
        Funzionalità dello Staff
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'staff',
            ), 'default', true
    );
    ?>" title="Crud Staff">     
        Gestisci Staff
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'user',
            ), 'default', true
    );
    ?>" title="Elimina Users">     
        Elimina Utenti
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'statistiche',
            ), 'default', true
    );
    ?>" title="Statistiche Annuali">     
        Statistiche Annuali
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'faq',
            ), 'default', true
    );
    ?>" title="Crud Faq">     
        Gestione FAQ
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => '',
        'action' => '',
            ), 'default', true
    );
    ?>" title="chat" style="border-right: 2px solid #333;">     
        Vai alla Chat
    </a>

</nav>

<h3 class="headerAdmin">
    Gestisci gli Utenti Staff
</h3>

<div style="margin-left: 100px">
    <table class="tableAdmin" style="width: 900px;" border="">
        <tr>
            <th style="width: 300px"> Username </th> 
            <th style="width: 300px"> Nome </th> 
            <th style="width: 300px"> Cognome </th> 
        </tr>
    </table>

    <?php foreach ($this->staff as $staff) : ?>
        <table class="tableAdmin" style="width: 900px; " border="">
            <tbody>
                <tr>
                    <td style="width: 300px"><?php echo '' . $staff->username  . '' ?></td>
                    <td style="width: 300px"><?php echo'' . $staff->nome . '' ?></td>
                    <td style="width: 300px"><?php echo'' . $staff->cognome . '' ?></td>
                </tr>
            </tbody>
        </table>
    <?php endforeach ?>

</div>

<fieldset style="width: 300px; float: left;">
    <legend> <h3 class="headerAdmin"> Inserisci un nuovo Utente Staff </h3> </legend>
    <?php echo $this->inserisciForm; ?>
</fieldset>

<fieldset style="width: 300px; margin-left: 770px; ">
    <legend> <h3 class="headerAdmin"> Modifica o Elimina un Utente Staff </h3> </legend>
    <?php echo $this->crudForm; ?>
    <?php if ($this->user !== null): ?>

        <h3 class="headerAdmin"> Inserisci i nuovi dati </h3>
        <?php echo $this->modificaForm->populate($this->user);?>

    <?php endif; ?>

</fieldset>