<h2 class="headerAdmin">
    Area Riservata Amministratore
</h2>

<nav class="barraNavigazioneAdmin">
    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
            ), 'default', true
    );
    ?>" title="Operazioni Staff">     
        Funzionalità dello Staff
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'staff',
            ), 'default', true
    );
    ?>" title="Crud Staff">     
        Gestisci Staff
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'user',
            ), 'default', true
    );
    ?>" title="Elimina Users">     
        Elimina Utenti
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'statistiche',
            ), 'default', true
    );
    ?>" title="Statistiche Annuali">     
        Statistiche Annuali
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'faq',
            ), 'default', true
    );
    ?>" title="Crud Faq">     
        Gestione FAQ
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'chat',
            ), 'default', true
    );
    ?>" title="Assistenza" style="border-right: 2px solid #333;">     
        Vai alla chat
    </a>

</nav>

<h3 class="headerAdmin">
    Statistiche annuali delle prenotazioni
</h3>

<div style="margin-left: 150px">
    <table class="tableAdmin" style="width: 800px;" border="">
        <tr>
            <th style="width: 400px"> Mese </th> 
            <th style="width: 400px"> Numero Prenotazioni </th>
        </tr>
    </table>

    <?php for( $i=1;  $i <=12 ; $i++) : ?>
        <table class="tableAdmin" style="width: 800px; " border="">
            <tbody>
                <tr>
                    <td style="width: 400px"><?php echo '' . date('F', mktime(0, 0, 0, $i, 10)) . '' ?></td>
                    <td style="width: 400px"><?php echo'' . $this->stats[$i] . '' ?></td>
                </tr>
            </tbody>
        </table>
    <?php endfor ?>

</div>