<h2>
    Area Riservata Amministratore
</h2>

<nav style="width: 500px;float: left; margin-left: 1em">
    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
            ), 'default', true
    );
    ?>" title="Operazioni Staff">     
        Funzionalità dello Staff
    </a>

    <br>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'staff',
            ), 'default', true
    );
    ?>" title="Crud Staff">     
        Gestisci Staff
    </a>

    <br>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'user',
            ), 'default', true
    );
    ?>" title="Elimina Users">     
        Elimina Utenti
    </a>
    
    <br>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'statistiche',
            ), 'default', true
    );
    ?>" title="Statistiche Annuali">     
        Statistiche Annuali
    </a>
    
    <br> 
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'faq',
            ), 'default', true
    );
    ?>" title="Crud Faq">     
        Gestione FAQ
    </a>

</nav>

<h3>
    Statistiche annuali delle prenotazioni
</h3>

<div style="float: right; margin-right: 150px">
    <table style="background-color:#eee859; border-collapse:collapse; width: 800px; " border="">
        <tr>
            <th style="width: 200px"> Mese </th> 
            <th style="width: 200px"> Numero Prenotazioni </th>
        </tr>
    </table>

    <?php for( $i=1;  $i <=12 ; $i++) : ?>
        <table style="background-color:#eee859; border-collapse:collapse; width: 800px; " border="">
            <tbody>
                <tr>
                    <td style="width: 200px"><?php echo '' . date('F', mktime(0, 0, 0, $i, 10)) . '' ?></td>
                    <td style="width: 200px"><?php echo'' . $this->stats[$i] . '' ?></td>
                </tr>
            </tbody>
        </table>
    <?php endfor ?>

</div>