<h2 class="headerAdmin">
    Area Riservata Amministratore
</h2>

<nav class="barraNavigazioneAdmin">
    <a href="<?=
    $this->url(array(
        'controller' => 'staff',
        'action' => 'staffarea',
            ), 'default', true
    );
    ?>" title="Operazioni Staff">     
        Funzionalità dello Staff
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'staff',
            ), 'default', true
    );
    ?>" title="Crud Staff">     
        Gestisci Staff
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'user',
            ), 'default', true
    );
    ?>" title="Elimina Users">     
        Elimina Utenti
    </a>

    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'statistiche',
            ), 'default', true
    );
    ?>" title="Statistiche Annuali">     
        Statistiche Annuali
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'faq',
            ), 'default', true
    );
    ?>" title="Crud Faq">     
        Gestione FAQ
    </a>
    
    <a href="<?=
    $this->url(array(
        'controller' => 'admin',
        'action' => 'chat',
            ), 'default', true
    );
    ?>" title="Assistenza" style="border-right: 2px solid #333;">     
        Vai alla chat
    </a>

</nav>

<h3 class="headerAdmin">
    Cancella un Utente user
</h3>

<fieldset style="width: 200px; margin-left: 430px;">
    <legend> <h3 class="headerAdmin"> Scegli gli username degli utenti da eliminare </h3> </legend>
    <?php echo $this->eliminaUtenteForm; ?>
</fieldset>